CM\UserBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: CM\UserBundle\Entity\RoleRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
