parameters:
#    cm_project.example.class: CM\ProjectBundle\Example

services:
#    cm_project.example:
#        class: %cm_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
