parameters:
#    cm_theme.example.class: CM\ThemeBundle\Example

services:
#    cm_theme.example:
#        class: %cm_theme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
