CMDesktopBundle_homepage:
    pattern:  /
    defaults: { _controller: CMDesktopBundle:Default:index }
CMDesktopBundle_login:
    pattern:  /login
    defaults: { _controller: CMDesktopBundle:Default:login }
