CMDesktopBundle_homepage:
    pattern:  /
    defaults: { _controller: CMDesktopBundle:Default:index }
CMDesktopBundle_login:
    pattern:  /login
    defaults: { _controller: CMDesktopBundle:Default:login }
CMDesktopBundle_getProjects:
    pattern:  /getProjects
    defaults: { _controller: CMDesktopBundle:Default:getProjects }
CMDesktopBundle_getTasks:
    pattern:  /getTasks
    defaults: { _controller: CMDesktopBundle:Default:getTasks }
