parameters:
#    cm_desktop.example.class: CM\DesktopBundle\Example

services:
#    cm_desktop.example:
#        class: %cm_desktop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
